version: '3.8'

services:
  blazorwasm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blazorwasm
    ports:
      - "8085:80"
    restart: unless-stopped

    # opcional (melhor prática)
    deploy:
      resources:
        limits:
          memory: 512M
